sudo: required
language: ruby
cache: bundler

services:
  - docker


before_install:
  - docker info
  - gem install bundler --no-document

env:
  - PLATFORM=ubuntu
  - PLATFORM=centos
  - PLATFORM=amazon

script: bundle exec kitchen test ${PLATFORM}
